name: movie
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_spinkit: 5.0.0
  responsive_framework: 0.1.6
  google_fonts: ^4.0.3
  youtube_explode_dart: ^1.12.4
  lucide_icons: ^0.144.0
  flick_video_player: ^0.5.0
  visibility_detector: ^0.4.0+2
  cached_network_image: ^3.2.3
  auto_size_text: ^3.0.0
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0
  delayed_widget: ^1.1.2
  url_launcher: ^6.1.11
  anim_search_bar: ^2.0.3
  easy_animated_tabbar: ^0.0.1
  grouped_list: ^5.1.2
  animated_text_kit: ^4.2.2
  hive: ^2.2.3
  connectivity: ^3.0.6
  flutter_vibrate: ^1.3.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Posters/kImage1.jpg
    - assets/Posters/kImage2.jpg
    - assets/Posters/kImage3.jpg
    - assets/Posters/kImage4.jpg
    - assets/Posters/kImage5.jpg
    - assets/Posters/kImage6.jpg
    - assets/Posters/kImage7.jpg
    - assets/Posters/kImage8.jpg
    - assets/Posters/kImage9.jpg
    - assets/Posters/kImage10.jpg
    - assets/Posters/kImage11.jpg
    - assets/Posters/kImage12.jpg
    - assets/Posters/kImage13.jpg
    - assets/Posters/kImage14.jpg
    - assets/Posters/kImage15.jpg
    - assets/Posters/kImage16.jpg
    - assets/Posters/kImage17.jpg
    - assets/Posters/kImage18.jpg
    - assets/Posters/kImage19.jpg
    - assets/Posters/kImage20.jpg
    - assets/Posters/kImage21.jpg

